### ISSUE TITLE
Bugs for edit

### ISSUE THREAD

**Issue by chrisjwelly** [AY1920S2-CS2103T-F10-1/main#191]
- [x] Skill cannot be edited for its level only. Name has to be supplied (Update; for some reason this is all ok in the latest main)
- [x] w/ prefix changes description instead of website
- [x] Editing a project to the same name as others doesn't give error messages (if they both have the same time)
- [x] Editing a project to the same name as others will pass through if they both have different time

**Comment by wardetu** [comment]
We are okay with the last case since you can do the same project in two different times.
